version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis  # Redis servisini bekle
    networks:
      - app_network
    environment:
      - REDIS_HOST=redis  # Django'nun Redis'e bağlanması için kullanılacak ortam değişkeni

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Redis portunu expose ediyoruz
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
