# Generated by Django 5.1.3 on 2024-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geo_lat',
            field=models.DecimalField(decimal_places=6, max_digits=20,default=0.0),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_lng',
            field=models.DecimalField(decimal_places=6, max_digits=20,default=0.0),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
