# Generated by Django 5.1.3 on 2024-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_address_geo_lat_alter_address_geo_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True,default=0.0),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True,default=0.0),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(max_length=255),
        ),
    ]
